"""Dish-name translations for the delivery notification email (Part 72).

MANUAL COPY of static/i18n.js's own DISH_NAME_LABELS -- kept here rather
than loaded from one shared source because i18n.js is loaded synchronously
by every render in the browser (see dishNameLabel()'s callers throughout
static/app.js) while this module only needs it for the one place Python
ever has to show a dish name in a language other than French: building
the courier's delivery-notification email (see mailer.py's
_triple_dish_names()). Same closed-vocabulary rule as the JS original --
a name not covered here is shown as Restopolis itself wrote it, never
guessed at runtime. The first 27 entries were human-checked; the fixed-
product entries added afterwards (sandwiches, viennoiseries, dairy, ice
cream, drinks, packaging) were drafted by Claude in one pass and still
need a native speaker's review, above all for zh/hi/ar/bn/ur/lb.

Whenever a name is added to static/i18n.js's DISH_NAME_LABELS, add the
same entry here too (or regenerate this file -- see the git history of
this file for the one-off script that built it from i18n.js).
"""

from __future__ import annotations

DEFAULT_LANG = "en"

DISH_NAME_LABELS: dict[str, dict[str, str]] = {
    "Banane \"commerce équitable\"": {
        "en": "Fair trade banana",
        "zh": "公平贸易香蕉",
        "hi": "फेयर ट्रेड केला",
        "es": "Plátano de comercio justo",
        "fr": "Banane \"commerce équitable\"",
        "ar": "موز تجارة عادلة",
        "bn": "ফেয়ার ট্রেড কলা",
        "pt": "Banana de comércio justo",
        "ru": "Банан справедливой торговли",
        "ur": "فیئر ٹریڈ کیلا",
        "lb": "Fair-Trade Banann"
    },
    "Barquette pour pâtes/salades à emporter": {
        "en": "Takeaway container for pasta/salads",
        "zh": "意面/沙拉外带餐盒",
        "hi": "पास्ता/सलाद टेकअवे कंटेनर",
        "es": "Envase para llevar de pasta/ensaladas",
        "fr": "Barquette pour pâtes/salades à emporter",
        "ar": "علبة للطلب الخارجي للمعكرونة/السلطات",
        "bn": "পাস্তা/সালাদ টেকঅ্যাওয়ে বাক্স",
        "pt": "Embalagem para levar de massa/saladas",
        "ru": "Контейнер навынос для пасты/салатов",
        "ur": "پاستا/سلاد ٹیک اوے کنٹینر",
        "lb": "Matnehm-Këscht fir Zalot/Nuddelen"
    },
    "Café \"commerce équitable\"": {
        "en": "Fair trade coffee",
        "zh": "公平贸易咖啡",
        "hi": "फेयर ट्रेड कॉफ़ी",
        "es": "Café de comercio justo",
        "fr": "Café \"commerce équitable\"",
        "ar": "قهوة تجارة عادلة",
        "bn": "ফেয়ার ট্রেড কফি",
        "pt": "Café de comércio justo",
        "ru": "Кофе справедливой торговли",
        "ur": "فیئر ٹریڈ کافی",
        "lb": "Fair-Trade Kaffi"
    },
    "Carottes persillées": {
        "en": "Parsleyed carrots",
        "zh": "欧芹胡萝卜",
        "hi": "अजमोद के साथ गाजर",
        "es": "Zanahorias al perejil",
        "fr": "Carottes persillées",
        "ar": "جزر بالبقدونس",
        "bn": "পার্সলে গাজর",
        "pt": "Cenouras com salsa",
        "ru": "Морковь с петрушкой",
        "ur": "اجمود کے ساتھ گاجر",
        "lb": "Muert mat Peitercili"
    },
    "Chocolat chaud \"Commerce équitable\"": {
        "en": "Fair trade hot chocolate",
        "zh": "公平贸易热巧克力",
        "hi": "फेयर ट्रेड हॉट चॉकलेट",
        "es": "Chocolate caliente de comercio justo",
        "fr": "Chocolat chaud \"Commerce équitable\"",
        "ar": "شوكولاتة ساخنة تجارة عادلة",
        "bn": "ফেয়ার ট্রেড হট চকোলেট",
        "pt": "Chocolate quente de comércio justo",
        "ru": "Горячий шоколад справедливой торговли",
        "ur": "فیئر ٹریڈ ہاٹ چاکلیٹ",
        "lb": "Fair-Trade waarme Kakao"
    },
    "Couvercle pour barquette à emporter": {
        "en": "Lid for takeaway container",
        "zh": "外带餐盒盖",
        "hi": "टेकअवे कंटेनर का ढक्कन",
        "es": "Tapa para envase para llevar",
        "fr": "Couvercle pour barquette à emporter",
        "ar": "غطاء لعلبة الطلب الخارجي",
        "bn": "টেকঅ্যাওয়ে বাক্সের ঢাকনা",
        "pt": "Tampa para embalagem para levar",
        "ru": "Крышка для контейнера навынос",
        "ur": "ٹیک اوے کنٹینر کا ڈھکن",
        "lb": "Deckel fir Matnehm-Këscht"
    },
    "Cuillère comestible": {
        "en": "Edible spoon",
        "zh": "可食用勺子",
        "hi": "खाने योग्य चम्मच",
        "es": "Cuchara comestible",
        "fr": "Cuillère comestible",
        "ar": "ملعقة صالحة للأكل",
        "bn": "ভোজ্য চামচ",
        "pt": "Colher comestível",
        "ru": "Съедобная ложка",
        "ur": "کھانے کے قابل چمچ",
        "lb": "Iessbar Läffel"
    },
    "Dessert du Jour": {
        "en": "Dessert of the day",
        "zh": "今日甜点",
        "hi": "आज का मिठाई",
        "es": "Postre del día",
        "fr": "Dessert du Jour",
        "ar": "حلوى اليوم",
        "bn": "আজকের ডেজার্ট",
        "pt": "Sobremesa do dia",
        "ru": "Десерт дня",
        "ur": "آج کا میٹھا",
        "lb": "Dessert vum Dag"
    },
    "Faux-filet de boeuf grillé sauce Béarnaise": {
        "en": "Grilled beef sirloin with Béarnaise sauce",
        "zh": "烤牛排配贝亚恩酱",
        "hi": "बियर्नेज़ सॉस के साथ ग्रिल्ड बीफ़ सिरलॉइन",
        "es": "Solomillo de ternera a la parrilla con salsa bearnesa",
        "fr": "Faux-filet de boeuf grillé sauce Béarnaise",
        "ar": "شريحة لحم بقري مشوية بصلصة البيارنيز",
        "bn": "বেয়ারনেজ সসসহ গ্রিলড বিফ সিরলোইন",
        "pt": "Lombo de vaca grelhado com molho bearnaise",
        "ru": "Жареный говяжий стейк с соусом беарнез",
        "ur": "بیئرنیز ساس کے ساتھ گرل بیف سرلوئن",
        "lb": "Gegrillten Rëndsentrecote mat Bearnaise-Zooss"
    },
    "Fourchette en bois": {
        "en": "Wooden fork",
        "zh": "木叉",
        "hi": "लकड़ी का काँटा",
        "es": "Tenedor de madera",
        "fr": "Fourchette en bois",
        "ar": "شوكة خشبية",
        "bn": "কাঠের কাঁটাচামচ",
        "pt": "Garfo de madeira",
        "ru": "Деревянная вилка",
        "ur": "لکڑی کا کانٹا",
        "lb": "Holzgabel"
    },
    "Fruit frais entier": {
        "en": "Whole fresh fruit",
        "zh": "新鲜水果（整个）",
        "hi": "साबुत ताज़ा फल",
        "es": "Fruta fresca entera",
        "fr": "Fruit frais entier",
        "ar": "فاكهة طازجة كاملة",
        "bn": "গোটা তাজা ফল",
        "pt": "Fruta fresca inteira",
        "ru": "Целый свежий фрукт",
        "ur": "پورا تازہ پھل",
        "lb": "Ganz frësch Uebst"
    },
    "Gobelet comestible 220 ml": {
        "en": "Edible cup 220 ml",
        "zh": "可食用杯 220 毫升",
        "hi": "खाने योग्य कप 220 मिली",
        "es": "Vaso comestible 220 ml",
        "fr": "Gobelet comestible 220 ml",
        "ar": "كوب صالح للأكل 220 مل",
        "bn": "ভোজ্য কাপ ২২০ মিলি",
        "pt": "Copo comestível 220 ml",
        "ru": "Съедобный стакан 220 мл",
        "ur": "کھانے کے قابل کپ 220 ملی",
        "lb": "Iessbar Becher 220 ml"
    },
    "Mini fruits découpés mélangés/non-mélangés 150 g": {
        "en": "Mini cut fruit, mixed/plain 150 g",
        "zh": "迷你切块水果（混合/单一）150克",
        "hi": "मिनी कटे फल, मिश्रित/सादा 150 ग्राम",
        "es": "Mini fruta cortada, mixta/sencilla 150 g",
        "fr": "Mini fruits découpés mélangés/non-mélangés 150 g",
        "ar": "فواكه مقطعة صغيرة، مشكلة/فردية 150 غ",
        "bn": "মিনি কাটা ফল, মিশ্র/সাধারণ ১৫০ গ্রাম",
        "pt": "Mini fruta cortada, mista/simples 150 g",
        "ru": "Мини нарезанные фрукты, смешанные/обычные 150 г",
        "ur": "منی کٹے پھل، ملے جلے/سادہ 150 گرام",
        "lb": "Mini geschniddent Uebst, gemëscht/eenzel 150 g"
    },
    "Mini salades 150 g": {
        "en": "Mini salads 150 g",
        "zh": "迷你沙拉 150克",
        "hi": "मिनी सलाद 150 ग्राम",
        "es": "Mini ensaladas 150 g",
        "fr": "Mini salades 150 g",
        "ar": "سلطات صغيرة 150 غ",
        "bn": "মিনি সালাদ ১৫০ গ্রাম",
        "pt": "Mini saladas 150 g",
        "ru": "Мини-салаты 150 г",
        "ur": "منی سلاد 150 گرام",
        "lb": "Mini Zalot 150 g"
    },
    "Petit bol de potage": {
        "en": "Small bowl of soup",
        "zh": "小份浓汤",
        "hi": "छोटा सूप का कटोरा",
        "es": "Tazón pequeño de sopa",
        "fr": "Petit bol de potage",
        "ar": "وعاء صغير من الحساء",
        "bn": "ছোট বাটি স্যুপ",
        "pt": "Taça pequena de sopa",
        "ru": "Маленькая тарелка супа",
        "ur": "سوپ کا چھوٹا پیالہ",
        "lb": "Kleng Zopp-Schierbel"
    },
    "Poche aux pommes 80 g": {
        "en": "Apple turnover 80 g",
        "zh": "苹果酥饼 80克",
        "hi": "सेब टर्नओवर 80 ग्राम",
        "es": "Empanadilla de manzana 80 g",
        "fr": "Poche aux pommes 80 g",
        "ar": "فطيرة تفاح 80 غ",
        "bn": "আপেল টার্নওভার ৮০ গ্রাম",
        "pt": "Folhado de maçã 80 g",
        "ru": "Яблочный слоёный пирожок 80 г",
        "ur": "سیب کا ٹرن اوور 80 گرام",
        "lb": "Äppelzak 80 g"
    },
    "Pommes de terre grenailles rôties": {
        "en": "Roasted new potatoes",
        "zh": "烤小土豆",
        "hi": "भुनी हुई नई आलू",
        "es": "Patatas nuevas asadas",
        "fr": "Pommes de terre grenailles rôties",
        "ar": "بطاطس صغيرة محمصة",
        "bn": "রোস্ট করা নতুন আলু",
        "pt": "Batatas novas assadas",
        "ru": "Запечённый молодой картофель",
        "ur": "بھنے ہوئے نئے آلو",
        "lb": "Gebrode Fréikartoffelen"
    },
    "Rôti de porc Orloff, jus lié": {
        "en": "Pork roast Orloff, thickened jus",
        "zh": "奥尔洛夫烤猪肉配浓肉汁",
        "hi": "पोर्क रोस्ट ऑरलॉफ़, गाढ़ा जूस",
        "es": "Asado de cerdo Orloff, jugo ligado",
        "fr": "Rôti de porc Orloff, jus lié",
        "ar": "لحم خنزير روستو أورلوف مع صلصة مكثفة",
        "bn": "পোর্ক রোস্ট অরলফ, ঘন গ্রেভি",
        "pt": "Assado de porco Orloff, molho engrossado",
        "ru": "Свиное жаркое Орлов, загущённый соус",
        "ur": "پورک روسٹ اورلوف، گاڑھا جوس",
        "lb": "Schweinsbrode Orloff, gebonnene Jus"
    },
    "Sachet pour sandwiches": {
        "en": "Sandwich bag",
        "zh": "三明治袋",
        "hi": "सैंडविच बैग",
        "es": "Bolsa para sándwiches",
        "fr": "Sachet pour sandwiches",
        "ar": "كيس للسندويشات",
        "bn": "স্যান্ডউইচ ব্যাগ",
        "pt": "Saco para sandes",
        "ru": "Пакет для сэндвичей",
        "ur": "سینڈوچ بیگ",
        "lb": "Sandwich-Täitchen"
    },
    "Salade aux mezzés variés": {
        "en": "Salad with assorted mezze",
        "zh": "什锦前菜沙拉",
        "hi": "मिश्रित मेज़े सलाद",
        "es": "Ensalada con mezze variados",
        "fr": "Salade aux mezzés variés",
        "ar": "سلطة بالمقبلات المتنوعة",
        "bn": "বিভিন্ন মেজে সহ সালাদ",
        "pt": "Salada com mezze variados",
        "ru": "Салат с ассорти мезе",
        "ur": "مختلف مزے کے ساتھ سلاد",
        "lb": "Zalot mat verschiddene Mezze"
    },
    "Salade campagnarde": {
        "en": "Country salad",
        "zh": "乡村沙拉",
        "hi": "देहाती सलाद",
        "es": "Ensalada campestre",
        "fr": "Salade campagnarde",
        "ar": "سلطة ريفية",
        "bn": "গ্রাম্য সালাদ",
        "pt": "Salada camponesa",
        "ru": "Деревенский салат",
        "ur": "دیہاتی سلاد",
        "lb": "Bauereszalot"
    },
    "Serviette en papier (à partir de la 2e serviette)": {
        "en": "Paper napkin (from the 2nd napkin)",
        "zh": "纸巾（自第2张起收费）",
        "hi": "पेपर नैपकिन (दूसरे नैपकिन से)",
        "es": "Servilleta de papel (a partir de la 2.ª)",
        "fr": "Serviette en papier (à partir de la 2e serviette)",
        "ar": "منديل ورقي (من المنديل الثاني)",
        "bn": "কাগজের ন্যাপকিন (২য়টি থেকে)",
        "pt": "Guardanapo de papel (a partir do 2.º)",
        "ru": "Бумажная салфетка (со 2-й салфетки)",
        "ur": "کاغذی نیپکن (دوسرے نیپکن سے)",
        "lb": "Pabeier-Salvett (vun der 2. Salvett un)"
    },
    "Soupe de pommes de terre": {
        "en": "Potato soup",
        "zh": "土豆汤",
        "hi": "आलू का सूप",
        "es": "Sopa de patata",
        "fr": "Soupe de pommes de terre",
        "ar": "شوربة البطاطس",
        "bn": "আলুর স্যুপ",
        "pt": "Sopa de batata",
        "ru": "Картофельный суп",
        "ur": "آلو کا سوپ",
        "lb": "Kartoffelzopp"
    },
    "Thé \"commerce équitable\"": {
        "en": "Fair trade tea",
        "zh": "公平贸易茶",
        "hi": "फेयर ट्रेड चाय",
        "es": "Té de comercio justo",
        "fr": "Thé \"commerce équitable\"",
        "ar": "شاي تجارة عادلة",
        "bn": "ফেয়ার ট্রেড চা",
        "pt": "Chá de comércio justo",
        "ru": "Чай справедливой торговли",
        "ur": "فیئر ٹریڈ چائے",
        "lb": "Fair-Trade Téi"
    },
    "Tisane": {
        "en": "Herbal tea",
        "zh": "花草茶",
        "hi": "हर्बल चाय",
        "es": "Infusión de hierbas",
        "fr": "Tisane",
        "ar": "شاي أعشاب",
        "bn": "ভেষজ চা",
        "pt": "Chá de ervas",
        "ru": "Травяной чай",
        "ur": "جڑی بوٹیوں کی چائے",
        "lb": "Kraidentéi"
    },
    "Wrap aux falafels": {
        "en": "Falafel wrap",
        "zh": "法拉费卷饼",
        "hi": "फ़लाफ़ेल रैप",
        "es": "Wrap de falafel",
        "fr": "Wrap aux falafels",
        "ar": "راب فلافل",
        "bn": "ফালাফেল র‍্যাপ",
        "pt": "Wrap de falafel",
        "ru": "Ролл с фалафелем",
        "ur": "فلافل ریپ",
        "lb": "Falafel-Wrap"
    },
    "Wrap façon croque monsieur": {
        "en": "Croque monsieur-style wrap",
        "zh": "法式火腿芝士卷饼",
        "hi": "क्रोक-मस्यू शैली रैप",
        "es": "Wrap estilo croque monsieur",
        "fr": "Wrap façon croque monsieur",
        "ar": "راب على طريقة الكروك موسيو",
        "bn": "ক্রক মসিয়ে স্টাইল র‍্যাপ",
        "pt": "Wrap estilo croque monsieur",
        "ru": "Ролл в стиле крок-месье",
        "ur": "کروک موسیو انداز کا ریپ",
        "lb": "Wrap am Stil vum Croque Monsieur"
    },
    # --- fixed-product pass: drafted by Claude, not yet checked by native speakers (see i18n.js)
    "1/2 Levain \"Great César\"": {
        "en": "1/2 sourdough \"Great César\" sandwich",
        "zh": "1/2 酸种面包“Great César”三明治",
        "hi": "1/2 सावरडो \"ग्रेट सीज़र\" सैंडविच",
        "es": "1/2 sándwich de masa madre \"Great César\"",
        "fr": "1/2 Levain \"Great César\"",
        "ar": "نصف ساندويتش خبز مخمّر \"غريت سيزر\"",
        "bn": "১/২ সাওয়ারডো \"গ্রেট সিজার\" স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre \"Great César\"",
        "ru": "1/2 сэндвич на закваске «Great César»",
        "ur": "آدھا سوردو \"گریٹ سیزر\" سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich \"Great César\""
    },
    "1/2 Levain \"Pastrami\"": {
        "en": "1/2 sourdough pastrami sandwich",
        "zh": "1/2 酸种面包帕斯特拉米三明治",
        "hi": "1/2 सावरडो पास्त्रामी सैंडविच",
        "es": "1/2 sándwich de masa madre de pastrami",
        "fr": "1/2 Levain \"Pastrami\"",
        "ar": "نصف ساندويتش خبز مخمّر بالباسترمة",
        "bn": "১/২ সাওয়ারডো প্যাস্ট্রামি স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre de pastrami",
        "ru": "1/2 сэндвич на закваске с пастрами",
        "ur": "آدھا سوردو پاسترامی سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich mat Pastrami"
    },
    "1/2 Levain Humi (houmous aux légumes locaux grillés)": {
        "en": "1/2 sourdough Humi (hummus with grilled local vegetables)",
        "zh": "1/2 酸种面包 Humi（配烤本地蔬菜的鹰嘴豆泥）",
        "hi": "1/2 सावरडो हुमी (ग्रिल्ड स्थानीय सब्ज़ियों वाला हम्मस)",
        "es": "1/2 masa madre Humi (hummus con verduras locales a la parrilla)",
        "fr": "1/2 Levain Humi (houmous aux légumes locaux grillés)",
        "ar": "نصف خبز مخمّر هومي (حمّص مع خضار محلية مشوية)",
        "bn": "১/২ সাওয়ারডো হুমি (গ্রিল করা স্থানীয় সবজি সহ হুমুস)",
        "pt": "1/2 massa madre Humi (húmus com legumes locais grelhados)",
        "ru": "1/2 на закваске Humi (хумус с местными овощами-гриль)",
        "ur": "آدھا سوردو ہومی (گرل کی ہوئی مقامی سبزیوں کے ساتھ حمس)",
        "lb": "1/2 Sauerteg Humi (Hummus mat gegrëlltem lokalem Geméis)"
    },
    "1/2 Levain Parmigiana Sandwich": {
        "en": "1/2 sourdough Parmigiana sandwich",
        "zh": "1/2 酸种面包帕尔米贾纳三明治",
        "hi": "1/2 सावरडो परमिजियाना सैंडविच",
        "es": "1/2 sándwich de masa madre Parmigiana",
        "fr": "1/2 Levain Parmigiana Sandwich",
        "ar": "نصف ساندويتش خبز مخمّر بارميجيانا",
        "bn": "১/২ সাওয়ারডো পারমিজিয়ানা স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre Parmigiana",
        "ru": "1/2 сэндвич на закваске «Пармиджана»",
        "ur": "آدھا سوردو پارمیجیانا سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich Parmigiana"
    },
    "1/2 Levain The ultimate egg Sandwich": {
        "en": "1/2 sourdough ultimate egg sandwich",
        "zh": "1/2 酸种面包终极鸡蛋三明治",
        "hi": "1/2 सावरडो अल्टीमेट एग सैंडविच",
        "es": "1/2 sándwich de masa madre The ultimate egg",
        "fr": "1/2 Levain The ultimate egg Sandwich",
        "ar": "نصف ساندويتش خبز مخمّر بالبيض (ذا ألتيميت)",
        "bn": "১/২ সাওয়ারডো আলটিমেট এগ স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre The ultimate egg",
        "ru": "1/2 сэндвич на закваске «The ultimate egg»",
        "ur": "آدھا سوردو الٹیمیٹ ایگ سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich The ultimate egg"
    },
    "1/2 Levain Tortilla Olé": {
        "en": "1/2 sourdough Tortilla Olé sandwich",
        "zh": "1/2 酸种面包 Tortilla Olé 三明治",
        "hi": "1/2 सावरडो टॉर्टिला ओले सैंडविच",
        "es": "1/2 sándwich de masa madre Tortilla Olé",
        "fr": "1/2 Levain Tortilla Olé",
        "ar": "نصف ساندويتش خبز مخمّر تورتيلا أوليه",
        "bn": "১/২ সাওয়ারডো টর্টিলা ওলে স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre Tortilla Olé",
        "ru": "1/2 сэндвич на закваске «Тортилья Оле»",
        "ur": "آدھا سوردو ٹورٹیلا اولے سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich Tortilla Olé"
    },
    "1/2 Levain fromage": {
        "en": "1/2 sourdough sandwich with cheese",
        "zh": "1/2 酸种面包奶酪三明治",
        "hi": "1/2 सावरडो चीज़ सैंडविच",
        "es": "1/2 sándwich de masa madre con queso",
        "fr": "1/2 Levain fromage",
        "ar": "نصف ساندويتش خبز مخمّر بالجبن",
        "bn": "১/২ সাওয়ারডো চিজ স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre com queijo",
        "ru": "1/2 сэндвич на закваске с сыром",
        "ur": "آدھا سوردو پنیر سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich mat Kéis"
    },
    "1/2 Levain jambon cuit": {
        "en": "1/2 sourdough sandwich with cooked ham",
        "zh": "1/2 酸种面包熟火腿三明治",
        "hi": "1/2 सावरडो पकी हैम सैंडविच",
        "es": "1/2 sándwich de masa madre con jamón cocido",
        "fr": "1/2 Levain jambon cuit",
        "ar": "نصف ساندويتش خبز مخمّر بالهام المطبوخ",
        "bn": "১/২ সাওয়ারডো রান্না করা হ্যাম স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre com fiambre",
        "ru": "1/2 сэндвич на закваске с вареной ветчиной",
        "ur": "آدھا سوردو پکا ہوا ہیم سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich mat gekachtem Schinken"
    },
    "1/2 Levain salami": {
        "en": "1/2 sourdough sandwich with salami",
        "zh": "1/2 酸种面包萨拉米三明治",
        "hi": "1/2 सावरडो सलामी सैंडविच",
        "es": "1/2 sándwich de masa madre con salami",
        "fr": "1/2 Levain salami",
        "ar": "نصف ساندويتش خبز مخمّر بالسلامي",
        "bn": "১/২ সাওয়ারডো সালামি স্যান্ডউইচ",
        "pt": "1/2 sanduíche de massa madre com salame",
        "ru": "1/2 сэндвич на закваске с салями",
        "ur": "آدھا سوردو سلامی سینڈوچ",
        "lb": "1/2 Sauerteg-Sandwich mat Salami"
    },
    "1/2 tranche de pain": {
        "en": "1/2 slice of bread",
        "zh": "半片面包",
        "hi": "आधा स्लाइस ब्रेड",
        "es": "1/2 rebanada de pan",
        "fr": "1/2 tranche de pain",
        "ar": "نصف شريحة خبز",
        "bn": "আধা স্লাইস রুটি",
        "pt": "1/2 fatia de pão",
        "ru": "1/2 ломтика хлеба",
        "ur": "آدھا سلائس روٹی",
        "lb": "1/2 Schnëtt Brout"
    },
    "Bretzel salé 80 g": {
        "en": "Salted pretzel 80 g",
        "zh": "咸味扭结面包 80 g",
        "hi": "नमकीन प्रेट्ज़ेल 80 g",
        "es": "Pretzel salado 80 g",
        "fr": "Bretzel salé 80 g",
        "ar": "بريتزل مملح 80 g",
        "bn": "নোনতা প্রেটজেল 80 g",
        "pt": "Pretzel salgado 80 g",
        "ru": "Соленый претцель 80 g",
        "ur": "نمکین پریٹزل 80 g",
        "lb": "Gesalzene Bretzel 80 g"
    },
    "Cappuccino": {
        "en": "Cappuccino",
        "zh": "卡布奇诺",
        "hi": "कैपुचीनो",
        "es": "Capuchino",
        "fr": "Cappuccino",
        "ar": "كابتشينو",
        "bn": "ক্যাপুচিনো",
        "pt": "Cappuccino",
        "ru": "Капучино",
        "ur": "کیپوچینو",
        "lb": "Cappuccino"
    },
    "Ciabatta tomate-mozzarella et pesto": {
        "en": "Ciabatta with tomato, mozzarella and pesto",
        "zh": "番茄马苏里拉青酱恰巴塔面包",
        "hi": "टमाटर-मोज़ेरेला और पेस्टो चियाबट्टा",
        "es": "Chapata de tomate, mozzarella y pesto",
        "fr": "Ciabatta tomate-mozzarella et pesto",
        "ar": "شاباتا بالطماطم والموزاريلا والبيستو",
        "bn": "টমেটো-মোজারেলা ও পেস্তো চিয়াবাত্তা",
        "pt": "Ciabatta de tomate, mozzarella e pesto",
        "ru": "Чиабатта с томатом, моцареллой и песто",
        "ur": "ٹماٹر، موزاریلا اور پیسٹو والی چیاباتا",
        "lb": "Ciabatta mat Tomat, Mozzarella a Pesto"
    },
    "Consigne ECOBOX (1000 ml)": {
        "en": "ECOBOX deposit (1000 ml)",
        "zh": "ECOBOX 押金 (1000 ml)",
        "hi": "ECOBOX जमा राशि (1000 ml)",
        "es": "Depósito ECOBOX (1000 ml)",
        "fr": "Consigne ECOBOX (1000 ml)",
        "ar": "وديعة ECOBOX (1000 ml)",
        "bn": "ECOBOX জামানত (1000 ml)",
        "pt": "Depósito ECOBOX (1000 ml)",
        "ru": "Залог за ECOBOX (1000 ml)",
        "ur": "ECOBOX ڈپازٹ (1000 ml)",
        "lb": "ECOBOX-Pfand (1000 ml)"
    },
    "Consigne ECOBOX (500 ml)": {
        "en": "ECOBOX deposit (500 ml)",
        "zh": "ECOBOX 押金 (500 ml)",
        "hi": "ECOBOX जमा राशि (500 ml)",
        "es": "Depósito ECOBOX (500 ml)",
        "fr": "Consigne ECOBOX (500 ml)",
        "ar": "وديعة ECOBOX (500 ml)",
        "bn": "ECOBOX জামানত (500 ml)",
        "pt": "Depósito ECOBOX (500 ml)",
        "ru": "Залог за ECOBOX (500 ml)",
        "ur": "ECOBOX ڈپازٹ (500 ml)",
        "lb": "ECOBOX-Pfand (500 ml)"
    },
    "Cornet Luxlait 130 ml (Chocolat, Fraise, Vanille, Praliné, Mocca-vanille)": {
        "en": "Luxlait cone 130 ml (chocolate, strawberry, vanilla, praline, mocha-vanilla)",
        "zh": "Luxlait 甜筒 130 ml（巧克力、草莓、香草、果仁糖、摩卡香草）",
        "hi": "Luxlait कोन 130 ml (चॉकलेट, स्ट्रॉबेरी, वनीला, प्रालीन, मोका-वनीला)",
        "es": "Cono Luxlait 130 ml (chocolate, fresa, vainilla, praliné, moca-vainilla)",
        "fr": "Cornet Luxlait 130 ml (Chocolat, Fraise, Vanille, Praliné, Mocca-vanille)",
        "ar": "كورنيه Luxlait 130 ml (شوكولاتة، فراولة، فانيليا، برالين، موكا-فانيليا)",
        "bn": "Luxlait কোন 130 ml (চকোলেট, স্ট্রবেরি, ভ্যানিলা, প্রালিন, মোকা-ভ্যানিলা)",
        "pt": "Cone Luxlait 130 ml (chocolate, morango, baunilha, praliné, moca-baunilha)",
        "ru": "Рожок Luxlait 130 ml (шоколад, клубника, ваниль, пралине, мокко-ваниль)",
        "ur": "Luxlait کون 130 ml (چاکلیٹ، اسٹرابیری، ونیلا، پرالین، موکا-ونیلا)",
        "lb": "Luxlait Cornet 130 ml (Schockela, Äerbier, Vanill, Praliné, Mokka-Vanill)"
    },
    "Croissant 50 g": {
        "en": "Croissant 50 g",
        "zh": "牛角包 50 g",
        "hi": "क्रोसैं 50 g",
        "es": "Cruasán 50 g",
        "fr": "Croissant 50 g",
        "ar": "كرواسون 50 g",
        "bn": "ক্রোয়াসাঁ 50 g",
        "pt": "Croissant 50 g",
        "ru": "Круассан 50 g",
        "ur": "کروسانٹ 50 g",
        "lb": "Croissant 50 g"
    },
    "Croissant fourré 70 g": {
        "en": "Filled croissant 70 g",
        "zh": "夹心牛角包 70 g",
        "hi": "भरा हुआ क्रोसैं 70 g",
        "es": "Cruasán relleno 70 g",
        "fr": "Croissant fourré 70 g",
        "ar": "كرواسون محشو 70 g",
        "bn": "ভরা ক্রোয়াসাঁ 70 g",
        "pt": "Croissant recheado 70 g",
        "ru": "Круассан с начинкой 70 g",
        "ur": "بھرا ہوا کروسانٹ 70 g",
        "lb": "Gefëllte Croissant 70 g"
    },
    "Dame Blanche Luxlait 200 ml": {
        "en": "Luxlait Dame Blanche 200 ml",
        "zh": "Luxlait 白夫人冰淇淋 200 ml",
        "hi": "Luxlait डेम ब्लांश 200 ml",
        "es": "Dame Blanche Luxlait 200 ml",
        "fr": "Dame Blanche Luxlait 200 ml",
        "ar": "دام بلانش Luxlait 200 ml",
        "bn": "Luxlait ডাম ব্ল্যাঁশ 200 ml",
        "pt": "Dame Blanche Luxlait 200 ml",
        "ru": "Дам Бланш Luxlait 200 ml",
        "ur": "Luxlait ڈیم بلانش 200 ml",
        "lb": "Luxlait Dame Blanche 200 ml"
    },
    "Espresso": {
        "en": "Espresso",
        "zh": "意式浓缩咖啡",
        "hi": "एस्प्रेसो",
        "es": "Espresso",
        "fr": "Espresso",
        "ar": "إسبريسو",
        "bn": "এসপ্রেসো",
        "pt": "Espresso",
        "ru": "Эспрессо",
        "ur": "ایسپریسو",
        "lb": "Espresso"
    },
    "Espresso double": {
        "en": "Double espresso",
        "zh": "双份意式浓缩",
        "hi": "डबल एस्प्रेसो",
        "es": "Espresso doble",
        "fr": "Espresso double",
        "ar": "إسبريسو مزدوج",
        "bn": "ডাবল এসপ্রেসো",
        "pt": "Espresso duplo",
        "ru": "Двойной эспрессо",
        "ur": "ڈبل ایسپریسو",
        "lb": "Duebelen Espresso"
    },
    "Fuze Tea - Black Tea Pêche/Hibiscus 0,20 l btl": {
        "en": "Fuze Tea - Black Tea Peach/Hibiscus 0,20 l btl",
        "zh": "Fuze Tea - 红茶 桃子/洛神花 0,20 l btl",
        "hi": "Fuze Tea - ब्लैक टी आड़ू/हिबिस्कस 0,20 l btl",
        "es": "Fuze Tea - té negro melocotón/hibisco 0,20 l btl",
        "fr": "Fuze Tea - Black Tea Pêche/Hibiscus 0,20 l btl",
        "ar": "Fuze Tea - شاي أسود بالخوخ/الكركديه 0,20 l btl",
        "bn": "Fuze Tea - ব্ল্যাক টি পিচ/হিবিস্কাস 0,20 l btl",
        "pt": "Fuze Tea - chá preto pêssego/hibisco 0,20 l btl",
        "ru": "Fuze Tea - чёрный чай персик/гибискус 0,20 l btl",
        "ur": "Fuze Tea - بلیک ٹی آڑو/ہبسکس 0,20 l btl",
        "lb": "Fuze Tea - Schwaarzen Téi Peesch/Hibiskus 0,20 l btl"
    },
    "Fuze Tea - Black Tea Pêche/Hibiscus 0,40 l non consigné": {
        "en": "Fuze Tea - Black Tea Peach/Hibiscus 0,40 l non consigné",
        "zh": "Fuze Tea - 红茶 桃子/洛神花 0,40 l non consigné",
        "hi": "Fuze Tea - ब्लैक टी आड़ू/हिबिस्कस 0,40 l non consigné",
        "es": "Fuze Tea - té negro melocotón/hibisco 0,40 l non consigné",
        "fr": "Fuze Tea - Black Tea Pêche/Hibiscus 0,40 l non consigné",
        "ar": "Fuze Tea - شاي أسود بالخوخ/الكركديه 0,40 l non consigné",
        "bn": "Fuze Tea - ব্ল্যাক টি পিচ/হিবিস্কাস 0,40 l non consigné",
        "pt": "Fuze Tea - chá preto pêssego/hibisco 0,40 l non consigné",
        "ru": "Fuze Tea - чёрный чай персик/гибискус 0,40 l non consigné",
        "ur": "Fuze Tea - بلیک ٹی آڑو/ہبسکس 0,40 l non consigné",
        "lb": "Fuze Tea - Schwaarzen Téi Peesch/Hibiskus 0,40 l non consigné"
    },
    "Glace miniature Luxlait 100 ml (Framboise, Praliné, Vanille)": {
        "en": "Luxlait mini ice cream 100 ml (raspberry, praline, vanilla)",
        "zh": "Luxlait 迷你冰淇淋 100 ml（覆盆子、果仁糖、香草）",
        "hi": "Luxlait मिनी आइसक्रीम 100 ml (रास्पबेरी, प्रालीन, वनीला)",
        "es": "Mini helado Luxlait 100 ml (frambuesa, praliné, vainilla)",
        "fr": "Glace miniature Luxlait 100 ml (Framboise, Praliné, Vanille)",
        "ar": "آيس كريم صغير Luxlait 100 ml (توت العليق، برالين، فانيليا)",
        "bn": "Luxlait মিনি আইসক্রিম 100 ml (র‍্যাস্পবেরি, প্রালিন, ভ্যানিলা)",
        "pt": "Mini gelado Luxlait 100 ml (framboesa, praliné, baunilha)",
        "ru": "Мини-мороженое Luxlait 100 ml (малина, пралине, ваниль)",
        "ur": "Luxlait منی آئس کریم 100 ml (رسبری، پرالین، ونیلا)",
        "lb": "Luxlait Mini-Glace 100 ml (Himmbier, Praliné, Vanill)"
    },
    "Huit 80 g": {
        "en": "Figure-eight pastry 80 g",
        "zh": "八字形酥点 80 g",
        "hi": "आठ के आकार की पेस्ट्री 80 g",
        "es": "Pastel en forma de ocho 80 g",
        "fr": "Huit 80 g",
        "ar": "معجنات على شكل رقم ثمانية 80 g",
        "bn": "আট আকৃতির পেস্ট্রি 80 g",
        "pt": "Folhado em forma de oito 80 g",
        "ru": "Слойка в форме восьмерки 80 g",
        "ur": "آٹھ کی شکل کی پیسٹری 80 g",
        "lb": "Aachter-Gebäck 80 g"
    },
    "Lait Luxlait BIO 0,25 l Tétra Pack": {
        "en": "Luxlait organic milk 0,25 l Tétra Pack",
        "zh": "Luxlait 有机牛奶 0,25 l Tétra Pack",
        "hi": "Luxlait ऑर्गेनिक दूध 0,25 l Tétra Pack",
        "es": "Leche ecológica Luxlait 0,25 l Tétra Pack",
        "fr": "Lait Luxlait BIO 0,25 l Tétra Pack",
        "ar": "حليب عضوي Luxlait 0,25 l Tétra Pack",
        "bn": "Luxlait অর্গানিক দুধ 0,25 l Tétra Pack",
        "pt": "Leite biológico Luxlait 0,25 l Tétra Pack",
        "ru": "Органическое молоко Luxlait 0,25 l Tétra Pack",
        "ur": "Luxlait نامیاتی دودھ 0,25 l Tétra Pack",
        "lb": "Luxlait Bio-Mëllech 0,25 l Tétra Pack"
    },
    "Lait Luxlait BIO 0,25 l Tétra Pack (gratuit)": {
        "en": "Luxlait organic milk 0,25 l Tétra Pack (gratuit)",
        "zh": "Luxlait 有机牛奶 0,25 l Tétra Pack (gratuit)",
        "hi": "Luxlait ऑर्गेनिक दूध 0,25 l Tétra Pack (gratuit)",
        "es": "Leche ecológica Luxlait 0,25 l Tétra Pack (gratuit)",
        "fr": "Lait Luxlait BIO 0,25 l Tétra Pack (gratuit)",
        "ar": "حليب عضوي Luxlait 0,25 l Tétra Pack (gratuit)",
        "bn": "Luxlait অর্গানিক দুধ 0,25 l Tétra Pack (gratuit)",
        "pt": "Leite biológico Luxlait 0,25 l Tétra Pack (gratuit)",
        "ru": "Органическое молоко Luxlait 0,25 l Tétra Pack (gratuit)",
        "ur": "Luxlait نامیاتی دودھ 0,25 l Tétra Pack (gratuit)",
        "lb": "Luxlait Bio-Mëllech 0,25 l Tétra Pack (gratuit)"
    },
    "Lait chocolaté Luxlait 0,25 l Tétra Pack": {
        "en": "Luxlait chocolate milk 0,25 l Tétra Pack",
        "zh": "Luxlait 巧克力牛奶 0,25 l Tétra Pack",
        "hi": "Luxlait चॉकलेट दूध 0,25 l Tétra Pack",
        "es": "Leche con chocolate Luxlait 0,25 l Tétra Pack",
        "fr": "Lait chocolaté Luxlait 0,25 l Tétra Pack",
        "ar": "حليب بالشوكولاتة Luxlait 0,25 l Tétra Pack",
        "bn": "Luxlait চকোলেট দুধ 0,25 l Tétra Pack",
        "pt": "Leite com chocolate Luxlait 0,25 l Tétra Pack",
        "ru": "Шоколадное молоко Luxlait 0,25 l Tétra Pack",
        "ur": "Luxlait چاکلیٹ دودھ 0,25 l Tétra Pack",
        "lb": "Luxlait Schockelasmëllech 0,25 l Tétra Pack"
    },
    "Lodyss fine pétillante 0,25 l btl": {
        "en": "Lodyss lightly sparkling 0,25 l btl",
        "zh": "Lodyss 微气泡水 0,25 l btl",
        "hi": "Lodyss हल्की स्पार्कलिंग 0,25 l btl",
        "es": "Lodyss con gas suave 0,25 l btl",
        "fr": "Lodyss fine pétillante 0,25 l btl",
        "ar": "Lodyss فوّارة خفيفة 0,25 l btl",
        "bn": "Lodyss হালকা স্পার্কলিং 0,25 l btl",
        "pt": "Lodyss com gás suave 0,25 l btl",
        "ru": "Lodyss слабогазированная 0,25 l btl",
        "ur": "Lodyss ہلکی فِزی 0,25 l btl",
        "lb": "Lodyss liicht sprëtzeg 0,25 l btl"
    },
    "Lodyss plate 0,25 l btl": {
        "en": "Lodyss still 0,25 l btl",
        "zh": "Lodyss 无气泡水 0,25 l btl",
        "hi": "Lodyss सादा (बिना गैस) 0,25 l btl",
        "es": "Lodyss sin gas 0,25 l btl",
        "fr": "Lodyss plate 0,25 l btl",
        "ar": "Lodyss غير فوّارة 0,25 l btl",
        "bn": "Lodyss স্টিল (গ্যাস ছাড়া) 0,25 l btl",
        "pt": "Lodyss sem gás 0,25 l btl",
        "ru": "Lodyss негазированная 0,25 l btl",
        "ur": "Lodyss بغیر گیس 0,25 l btl",
        "lb": "Lodyss ouni Kuelesäure 0,25 l btl"
    },
    "Lët'z limo lemon & lime 0,33 btl": {
        "en": "Lët'z lemonade lemon & lime 0,33 btl",
        "zh": "Lët'z 柠檬青柠汽水 0,33 btl",
        "hi": "Lët'z लेमन-लाइम लिमोनेड 0,33 btl",
        "es": "Lët'z limonada de limón y lima 0,33 btl",
        "fr": "Lët'z limo lemon & lime 0,33 btl",
        "ar": "Lët'z ليموناضة بالليمون والليم 0,33 btl",
        "bn": "Lët'z লেবু ও লাইম লেমোনেড 0,33 btl",
        "pt": "Lët'z limonada de limão e lima 0,33 btl",
        "ru": "Lët'z лимонад лимон и лайм 0,33 btl",
        "ur": "Lët'z لیمن اینڈ لائم لیمونیڈ 0,33 btl",
        "lb": "Lët'z Limo Zitroun & Limett 0,33 btl"
    },
    "Lët'z limo orange 0,33 btl": {
        "en": "Lët'z lemonade orange 0,33 btl",
        "zh": "Lët'z 橙味汽水 0,33 btl",
        "hi": "Lët'z ऑरेंज लिमोनेड 0,33 btl",
        "es": "Lët'z limonada de naranja 0,33 btl",
        "fr": "Lët'z limo orange 0,33 btl",
        "ar": "Lët'z ليموناضة بالبرتقال 0,33 btl",
        "bn": "Lët'z কমলা লেমোনেড 0,33 btl",
        "pt": "Lët'z limonada de laranja 0,33 btl",
        "ru": "Lët'z лимонад апельсин 0,33 btl",
        "ur": "Lët'z اورنج لیمونیڈ 0,33 btl",
        "lb": "Lët'z Limo Orange 0,33 btl"
    },
    "Lëtzbuerger Drauwejus 0,25 l btl": {
        "en": "Luxembourg grape juice 0,25 l btl",
        "zh": "卢森堡葡萄汁 0,25 l btl",
        "hi": "लक्ज़मबर्ग अंगूर का रस 0,25 l btl",
        "es": "Zumo de uva de Luxemburgo 0,25 l btl",
        "fr": "Lëtzbuerger Drauwejus 0,25 l btl",
        "ar": "عصير عنب لوكسمبورغي 0,25 l btl",
        "bn": "লুক্সেমবার্গের আঙুরের রস 0,25 l btl",
        "pt": "Sumo de uva do Luxemburgo 0,25 l btl",
        "ru": "Люксембургский виноградный сок 0,25 l btl",
        "ur": "لکسمبرگ کا انگور کا رس 0,25 l btl",
        "lb": "Lëtzebuerger Drauwejus 0,25 l btl"
    },
    "Mini baguette sans gluten \"Schockelasbotter végan\"": {
        "en": "Gluten-free mini baguette with vegan \"Schockelasbotter\" (chocolate spread)",
        "zh": "无麸质迷你法棍配纯素巧克力酱“Schockelasbotter”",
        "hi": "ग्लूटेन-मुक्त मिनी बैगेट, वीगन \"Schockelasbotter\" (चॉकलेट स्प्रेड) के साथ",
        "es": "Mini baguette sin gluten con \"Schockelasbotter\" vegano (crema de chocolate)",
        "fr": "Mini baguette sans gluten \"Schockelasbotter végan\"",
        "ar": "ميني باجيت خالٍ من الغلوتين بدهن الشوكولاتة النباتي \"Schockelasbotter\"",
        "bn": "গ্লুটেন-মুক্ত মিনি ব্যাগেট, ভেগান \"Schockelasbotter\" (চকোলেট স্প্রেড) সহ",
        "pt": "Mini baguete sem glúten com \"Schockelasbotter\" vegano (creme de chocolate)",
        "ru": "Безглютеновый мини-багет с веганской шоколадной пастой «Schockelasbotter»",
        "ur": "گلوٹین فری منی بیگیٹ، ویگن \"Schockelasbotter\" (چاکلیٹ سپریڈ) کے ساتھ",
        "lb": "Glutenfräi Mini-Baguette mat vegane \"Schockelasbotter\""
    },
    "Mini baguette sans gluten fromage": {
        "en": "Gluten-free mini baguette with cheese",
        "zh": "无麸质奶酪迷你法棍",
        "hi": "पनीर वाला ग्लूटेन-मुक्त मिनी बैगेट",
        "es": "Mini baguette sin gluten con queso",
        "fr": "Mini baguette sans gluten fromage",
        "ar": "ميني باجيت خالٍ من الغلوتين بالجبن",
        "bn": "চিজ সহ গ্লুটেন-মুক্ত মিনি ব্যাগেট",
        "pt": "Mini baguete sem glúten com queijo",
        "ru": "Безглютеновый мини-багет с сыром",
        "ur": "پنیر والا گلوٹین فری منی بیگیٹ",
        "lb": "Glutenfräi Mini-Baguette mat Kéis"
    },
    "Mini baguette sans gluten jambon cuit": {
        "en": "Gluten-free mini baguette with cooked ham",
        "zh": "无麸质熟火腿迷你法棍",
        "hi": "पकी हैम वाला ग्लूटेन-मुक्त मिनी बैगेट",
        "es": "Mini baguette sin gluten con jamón cocido",
        "fr": "Mini baguette sans gluten jambon cuit",
        "ar": "ميني باجيت خالٍ من الغلوتين بالهام المطبوخ",
        "bn": "রান্না করা হ্যাম সহ গ্লুটেন-মুক্ত মিনি ব্যাগেট",
        "pt": "Mini baguete sem glúten com fiambre",
        "ru": "Безглютеновый мини-багет с вареной ветчиной",
        "ur": "پکے ہوئے ہیم والا گلوٹین فری منی بیگیٹ",
        "lb": "Glutenfräi Mini-Baguette mat gekachtem Schinken"
    },
    "Mini baguette sans gluten salami": {
        "en": "Gluten-free mini baguette with salami",
        "zh": "无麸质萨拉米迷你法棍",
        "hi": "सलामी वाला ग्लूटेन-मुक्त मिनी बैगेट",
        "es": "Mini baguette sin gluten con salami",
        "fr": "Mini baguette sans gluten salami",
        "ar": "ميني باجيت خالٍ من الغلوتين بالسلامي",
        "bn": "সালামি সহ গ্লুটেন-মুক্ত মিনি ব্যাগেট",
        "pt": "Mini baguete sem glúten com salame",
        "ru": "Безглютеновый мини-багет с салями",
        "ur": "سلامی والا گلوٹین فری منی بیگیٹ",
        "lb": "Glutenfräi Mini-Baguette mat Salami"
    },
    "Mini fromage frais avec coulis de fruits de saison 150 g": {
        "en": "Mini fresh cheese with seasonal fruit coulis 150 g",
        "zh": "迷你新鲜奶酪配时令水果酱 150 g",
        "hi": "मौसमी फलों की कूलिस के साथ मिनी ताज़ा पनीर 150 g",
        "es": "Mini queso fresco con coulis de frutas de temporada 150 g",
        "fr": "Mini fromage frais avec coulis de fruits de saison 150 g",
        "ar": "جبن طازج صغير مع صلصة فواكه موسمية 150 g",
        "bn": "মৌসুমি ফলের কুলিস সহ মিনি তাজা চিজ 150 g",
        "pt": "Mini queijo fresco com coulis de frutas da época 150 g",
        "ru": "Мини-творожный сыр с соусом из сезонных фруктов 150 g",
        "ur": "موسمی پھلوں کی کولس کے ساتھ منی تازہ پنیر 150 g",
        "lb": "Mini frëschen Kéis mat Coulis vu Saisonsuebst 150 g"
    },
    "Mini muesli maison \"Douceur d'automne\" 150 g": {
        "en": "Homemade mini muesli \"Autumn Delight\" 150 g",
        "zh": "自制迷你麦片“秋日甜蜜” 150 g",
        "hi": "घर का बना मिनी मूसली \"पतझड़ की मिठास\" 150 g",
        "es": "Mini muesli casero \"Dulzura de otoño\" 150 g",
        "fr": "Mini muesli maison \"Douceur d'automne\" 150 g",
        "ar": "موسلي منزلي صغير \"حلاوة الخريف\" 150 g",
        "bn": "বাড়িতে তৈরি মিনি মুসলি \"শরতের মিষ্টতা\" 150 g",
        "pt": "Mini muesli caseiro \"Doçura de outono\" 150 g",
        "ru": "Домашнее мини-мюсли «Осенняя нежность» 150 g",
        "ur": "گھر کا بنا منی مسلی \"خزاں کی مٹھاس\" 150 g",
        "lb": "Hausgemaachte Mini-Müsli \"Hierschtdouceur\" 150 g"
    },
    "Pain au chocolat 70 g": {
        "en": "Pain au chocolat 70 g",
        "zh": "巧克力面包 70 g",
        "hi": "पैन ऑ शॉकोला 70 g",
        "es": "Napolitana de chocolate 70 g",
        "fr": "Pain au chocolat 70 g",
        "ar": "بان أو شوكولا 70 g",
        "bn": "প্যাঁ ও শোকোলা 70 g",
        "pt": "Pain au chocolat 70 g",
        "ru": "Пэн-о-шоколя 70 g",
        "ur": "پین او شوکولا 70 g",
        "lb": "Pain au chocolat 70 g"
    },
    "Petit pain blanc \"Schockelasbotter végan\"": {
        "en": "White roll with vegan \"Schockelasbotter\" (chocolate spread)",
        "zh": "纯素巧克力酱白面包卷“Schockelasbotter”",
        "hi": "वीगन \"Schockelasbotter\" (चॉकलेट स्प्रेड) वाला सफ़ेद रोल",
        "es": "Panecillo blanco con \"Schockelasbotter\" vegano (crema de chocolate)",
        "fr": "Petit pain blanc \"Schockelasbotter végan\"",
        "ar": "خبز أبيض صغير بدهن الشوكولاتة النباتي \"Schockelasbotter\"",
        "bn": "ভেগান \"Schockelasbotter\" (চকোলেট স্প্রেড) সহ সাদা রোল",
        "pt": "Pãozinho branco com \"Schockelasbotter\" vegano (creme de chocolate)",
        "ru": "Белая булочка с веганской шоколадной пастой «Schockelasbotter»",
        "ur": "ویگن \"Schockelasbotter\" (چاکلیٹ سپریڈ) والا سفید رول",
        "lb": "Wäisst Brëtchen mat vegane \"Schockelasbotter\""
    },
    "Petit pain blanc fromage": {
        "en": "White roll with cheese",
        "zh": "奶酪白面包卷",
        "hi": "पनीर वाला सफ़ेद रोल",
        "es": "Panecillo blanco con queso",
        "fr": "Petit pain blanc fromage",
        "ar": "خبز أبيض صغير بالجبن",
        "bn": "চিজ দেওয়া সাদা রোল",
        "pt": "Pãozinho branco com queijo",
        "ru": "Белая булочка с сыром",
        "ur": "پنیر والا سفید رول",
        "lb": "Wäisst Brëtchen mat Kéis"
    },
    "Petit pain blanc jambon cuit": {
        "en": "White roll with cooked ham",
        "zh": "熟火腿白面包卷",
        "hi": "पकी हैम वाला सफ़ेद रोल",
        "es": "Panecillo blanco con jamón cocido",
        "fr": "Petit pain blanc jambon cuit",
        "ar": "خبز أبيض صغير بالهام المطبوخ",
        "bn": "রান্না করা হ্যাম দেওয়া সাদা রোল",
        "pt": "Pãozinho branco com fiambre",
        "ru": "Белая булочка с вареной ветчиной",
        "ur": "پکے ہوئے ہیم والا سفید رول",
        "lb": "Wäisst Brëtchen mat gekachtem Schinken"
    },
    "Petit pain blanc nature": {
        "en": "Plain white roll",
        "zh": "原味白面包卷",
        "hi": "सादा सफ़ेद रोल",
        "es": "Panecillo blanco natural",
        "fr": "Petit pain blanc nature",
        "ar": "خبز أبيض صغير سادة",
        "bn": "সাধারণ সাদা রোল",
        "pt": "Pãozinho branco simples",
        "ru": "Белая булочка без начинки",
        "ur": "سادہ سفید رول",
        "lb": "Nature wäisst Brëtchen"
    },
    "Petit pain blanc salami": {
        "en": "White roll with salami",
        "zh": "萨拉米白面包卷",
        "hi": "सलामी वाला सफ़ेद रोल",
        "es": "Panecillo blanco con salami",
        "fr": "Petit pain blanc salami",
        "ar": "خبز أبيض صغير بالسلامي",
        "bn": "সালামি দেওয়া সাদা রোল",
        "pt": "Pãozinho branco com salame",
        "ru": "Белая булочка с салями",
        "ur": "سلامی والا سفید رول",
        "lb": "Wäisst Brëtchen mat Salami"
    },
    "Remboursement Consigne ECOBOX (1000 ml)": {
        "en": "ECOBOX deposit refund (1000 ml)",
        "zh": "ECOBOX 押金退还 (1000 ml)",
        "hi": "ECOBOX जमा राशि की वापसी (1000 ml)",
        "es": "Devolución del depósito ECOBOX (1000 ml)",
        "fr": "Remboursement Consigne ECOBOX (1000 ml)",
        "ar": "استرداد وديعة ECOBOX (1000 ml)",
        "bn": "ECOBOX জামানত ফেরত (1000 ml)",
        "pt": "Reembolso do depósito ECOBOX (1000 ml)",
        "ru": "Возврат залога за ECOBOX (1000 ml)",
        "ur": "ECOBOX ڈپازٹ کی واپسی (1000 ml)",
        "lb": "ECOBOX-Pfand zréck (1000 ml)"
    },
    "Remboursement Consigne ECOBOX (500 ml)": {
        "en": "ECOBOX deposit refund (500 ml)",
        "zh": "ECOBOX 押金退还 (500 ml)",
        "hi": "ECOBOX जमा राशि की वापसी (500 ml)",
        "es": "Devolución del depósito ECOBOX (500 ml)",
        "fr": "Remboursement Consigne ECOBOX (500 ml)",
        "ar": "استرداد وديعة ECOBOX (500 ml)",
        "bn": "ECOBOX জামানত ফেরত (500 ml)",
        "pt": "Reembolso do depósito ECOBOX (500 ml)",
        "ru": "Возврат залога за ECOBOX (500 ml)",
        "ur": "ECOBOX ڈپازٹ کی واپسی (500 ml)",
        "lb": "ECOBOX-Pfand zréck (500 ml)"
    },
    "Rosport Sunny Citron-Citron vert 0,50 l non consigné": {
        "en": "Rosport Sunny Lemon-Lime 0,50 l non consigné",
        "zh": "Rosport Sunny 柠檬青柠 0,50 l non consigné",
        "hi": "Rosport Sunny नींबू-लाइम 0,50 l non consigné",
        "es": "Rosport Sunny Limón-Lima 0,50 l non consigné",
        "fr": "Rosport Sunny Citron-Citron vert 0,50 l non consigné",
        "ar": "Rosport Sunny ليمون وليم 0,50 l non consigné",
        "bn": "Rosport Sunny লেবু-লাইম 0,50 l non consigné",
        "pt": "Rosport Sunny Limão-Lima 0,50 l non consigné",
        "ru": "Rosport Sunny Лимон-лайм 0,50 l non consigné",
        "ur": "Rosport Sunny لیموں-لائم 0,50 l non consigné",
        "lb": "Rosport Sunny Zitroun-Limett 0,50 l non consigné"
    },
    "Rosport Sunny Pêche 0,50 l non consigné": {
        "en": "Rosport Sunny Peach 0,50 l non consigné",
        "zh": "Rosport Sunny 桃子 0,50 l non consigné",
        "hi": "Rosport Sunny आड़ू 0,50 l non consigné",
        "es": "Rosport Sunny Melocotón 0,50 l non consigné",
        "fr": "Rosport Sunny Pêche 0,50 l non consigné",
        "ar": "Rosport Sunny خوخ 0,50 l non consigné",
        "bn": "Rosport Sunny পিচ 0,50 l non consigné",
        "pt": "Rosport Sunny Pêssego 0,50 l non consigné",
        "ru": "Rosport Sunny Персик 0,50 l non consigné",
        "ur": "Rosport Sunny آڑو 0,50 l non consigné",
        "lb": "Rosport Sunny Peesch 0,50 l non consigné"
    },
    "Rosport mat Menthe 0,50 l non consigné": {
        "en": "Rosport with mint 0,50 l non consigné",
        "zh": "Rosport 薄荷味 0,50 l non consigné",
        "hi": "Rosport पुदीना फ़्लेवर 0,50 l non consigné",
        "es": "Rosport con menta 0,50 l non consigné",
        "fr": "Rosport mat Menthe 0,50 l non consigné",
        "ar": "Rosport بالنعناع 0,50 l non consigné",
        "bn": "Rosport পুদিনা 0,50 l non consigné",
        "pt": "Rosport com menta 0,50 l non consigné",
        "ru": "Rosport с мятой 0,50 l non consigné",
        "ur": "Rosport پودینہ 0,50 l non consigné",
        "lb": "Rosport mat Minz 0,50 l non consigné"
    },
    "Rosport mat Zitroun 0,50 l non consigné": {
        "en": "Rosport with lemon 0,50 l non consigné",
        "zh": "Rosport 柠檬味 0,50 l non consigné",
        "hi": "Rosport नींबू फ़्लेवर 0,50 l non consigné",
        "es": "Rosport con limón 0,50 l non consigné",
        "fr": "Rosport mat Zitroun 0,50 l non consigné",
        "ar": "Rosport بالليمون 0,50 l non consigné",
        "bn": "Rosport লেবু 0,50 l non consigné",
        "pt": "Rosport com limão 0,50 l non consigné",
        "ru": "Rosport с лимоном 0,50 l non consigné",
        "ur": "Rosport لیموں 0,50 l non consigné",
        "lb": "Rosport mat Zitroun 0,50 l non consigné"
    },
    "Streusel 80 g": {
        "en": "Streusel pastry 80 g",
        "zh": "酥粒糕点 80 g",
        "hi": "स्ट्रूज़ल पेस्ट्री 80 g",
        "es": "Bollo con streusel 80 g",
        "fr": "Streusel 80 g",
        "ar": "معجنات ستروسل 80 g",
        "bn": "স্ট্রয়সেল পেস্ট্রি 80 g",
        "pt": "Folhado com streusel 80 g",
        "ru": "Штрейзель 80 g",
        "ur": "اسٹروسل پیسٹری 80 g",
        "lb": "Streusel 80 g"
    },
    "Thermo Café 1,00 l": {
        "en": "Thermo coffee 1,00 l",
        "zh": "保温壶咖啡 1,00 l",
        "hi": "थर्मो कॉफ़ी 1,00 l",
        "es": "Café en termo 1,00 l",
        "fr": "Thermo Café 1,00 l",
        "ar": "قهوة في ترمس 1,00 l",
        "bn": "থার্মো কফি 1,00 l",
        "pt": "Café em termo 1,00 l",
        "ru": "Кофе в термосе 1,00 l",
        "ur": "تھرمو کافی 1,00 l",
        "lb": "Thermo-Kaffi 1,00 l"
    },
    "Thermo Café 1,50 l": {
        "en": "Thermo coffee 1,50 l",
        "zh": "保温壶咖啡 1,50 l",
        "hi": "थर्मो कॉफ़ी 1,50 l",
        "es": "Café en termo 1,50 l",
        "fr": "Thermo Café 1,50 l",
        "ar": "قهوة في ترمس 1,50 l",
        "bn": "থার্মো কফি 1,50 l",
        "pt": "Café em termo 1,50 l",
        "ru": "Кофе в термосе 1,50 l",
        "ur": "تھرمو کافی 1,50 l",
        "lb": "Thermo-Kaffi 1,50 l"
    },
    "Yaourt aux fruits Luxlait 125 g": {
        "en": "Luxlait fruit yoghurt 125 g",
        "zh": "Luxlait 水果酸奶 125 g",
        "hi": "Luxlait फल दही 125 g",
        "es": "Yogur de frutas Luxlait 125 g",
        "fr": "Yaourt aux fruits Luxlait 125 g",
        "ar": "زبادي بالفواكه Luxlait 125 g",
        "bn": "Luxlait ফলের দই 125 g",
        "pt": "Iogurte de frutas Luxlait 125 g",
        "ru": "Фруктовый йогурт Luxlait 125 g",
        "ur": "Luxlait پھلوں والا دہی 125 g",
        "lb": "Luxlait Uebstjoghurt 125 g"
    },
    "Yaourt nature Luxlait 125 g": {
        "en": "Luxlait plain yoghurt 125 g",
        "zh": "Luxlait 原味酸奶 125 g",
        "hi": "Luxlait सादा दही 125 g",
        "es": "Yogur natural Luxlait 125 g",
        "fr": "Yaourt nature Luxlait 125 g",
        "ar": "زبادي سادة Luxlait 125 g",
        "bn": "Luxlait প্লেইন দই 125 g",
        "pt": "Iogurte natural Luxlait 125 g",
        "ru": "Натуральный йогурт Luxlait 125 g",
        "ur": "Luxlait سادہ دہی 125 g",
        "lb": "Luxlait Natur-Joghurt 125 g"
    }
}


def dish_name_label(raw_name: str, lang: str) -> str:
    """Mirrors static/i18n.js's own dishNameLabel(): a real, human-checked
    translation when this specific Restopolis-written name is in the
    table above, else the raw name unchanged -- never a guessed/machine
    translation of arbitrary free text (see this module's docstring)."""
    entry = DISH_NAME_LABELS.get(raw_name)
    if entry is None:
        return raw_name
    return entry.get(lang) or entry.get(DEFAULT_LANG) or raw_name

